### ISSUE TITLE
Application restarts on Android 

### ISSUE THREAD

**Issue by adityathoutam** [yasirkula/UnityNativeCamera#29]
Application restarts on certain Android devices, when using this function

```c#
    private void TakePictureAfterPermissions(Texture2D monumentFilterLogo)
    {
        NativeCamera.TakePicture(path =>
        {
            if (path != null)
            {
                var Texture = NativeCamera.LoadImageAtPath(path, maxSize, false);
                if (Texture != null)
                {
                 // Applying Texture to RawImage
                }
            }
        }, maxSize, true, NativeCamera.PreferredCamera.Front);
    }
```

Here is the logcat generated

> 2020-02-03 12:04:08.465 24039-24196/? E/ImageUtils: decodeOrientation() - Fail to access file /devroot/data/data/APP_PACKAGE_NAME/cache/IMG_camera.jpg
>     java.io.FileNotFoundException: /devroot/data/data/APP_PACKAGE_NAME/cache/IMG_camera.jpg: open failed: ENOENT (No such file or directory)
>         at libcore.io.IoBridge.open(IoBridge.java:496)
>         at java.io.FileInputStream.<init>(FileInputStream.java:159)
>         at java.io.FileInputStream.<init>(FileInputStream.java:115)
>         at com.oneplus.media.ImageUtils.decodeOrientation(ImageUtils.java:1667)
>         at com.oneplus.camera.io.PhotoSaveTask.onPrepareMediaStoreValues(PhotoSaveTask.java:567)
>         at com.oneplus.camera.io.MediaSaveTask.insertToMediaStore(MediaSaveTask.java:260)
>         at com.oneplus.camera.io.PhotoSaveTask.insertToMediaStore(PhotoSaveTask.java:367)
>         at com.oneplus.camera.io.FileManagerImpl$FileManageerThread$1.handleMessage(FileManagerImpl.java:515)
>         at android.os.Handler.dispatchMessage(Handler.java:107)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.os.HandlerThread.run(HandlerThread.java:67)
>      Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
>         at libcore.io.Linux.open(Native Method)
>         at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
>         at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
>         at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
>         at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7581)
>         at libcore.io.IoBridge.open(IoBridge.java:482)
>         at java.io.FileInputStream.<init>(FileInputStream.java:159) 
>         at java.io.FileInputStream.<init>(FileInputStream.java:115) 
>         at com.oneplus.media.ImageUtils.decodeOrientation(ImageUtils.java:1667) 
>         at com.oneplus.camera.io.PhotoSaveTask.onPrepareMediaStoreValues(PhotoSaveTask.java:567) 
>         at com.oneplus.camera.io.MediaSaveTask.insertToMediaStore(MediaSaveTask.java:260) 
>         at com.oneplus.camera.io.PhotoSaveTask.insertToMediaStore(PhotoSaveTask.java:367) 
>         at com.oneplus.camera.io.FileManagerImpl$FileManageerThread$1.handleMessage(FileManagerImpl.java:515) 
>         at android.os.Handler.dispatchMessage(Handler.java:107) 
>         at android.os.Looper.loop(Looper.java:214) 
>         at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by yasirkula** [comment]
I've changed a code related to `IMG_camera.jpg`. Can you download the following zip, extract the **NativeCamera.aar** file inside it and replace the one inside `UNITY_PROJECT_PATH/Assets/Plugins/NativeCamera/Android` with it: [NativeCamera.zip](https://github.com/yasirkula/UnityNativeCamera/files/4152175/NativeCamera.zip)

**Comment by adityathoutam** [comment]
I have replaced the .aar file, but it still resulted in crash, here is the Logcat generated

> 2020-02-04 15:35:16.147 18113-18721/? E/ImageUtils: decodeOrientation() - Fail to access file /devroot/data/data/com.yatra.aah/cache/IMG_camera.jpg
    java.io.FileNotFoundException: /devroot/data/data/com.yatra.aah/cache/IMG_camera.jpg: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at com.oneplus.media.ImageUtils.decodeOrientation(ImageUtils.java:1667)
        at com.oneplus.camera.io.PhotoSaveTask.onPrepareMediaStoreValues(PhotoSaveTask.java:567)
        at com.oneplus.camera.io.MediaSaveTask.insertToMediaStore(MediaSaveTask.java:260)
        at com.oneplus.camera.io.PhotoSaveTask.insertToMediaStore(PhotoSaveTask.java:367)
        at com.oneplus.camera.io.FileManagerImpl$FileManageerThread$1.handleMessage(FileManagerImpl.java:515)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7581)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        at java.io.FileInputStream.<init>(FileInputStream.java:159) 
        at java.io.FileInputStream.<init>(FileInputStream.java:115) 
        at com.oneplus.media.ImageUtils.decodeOrientation(ImageUtils.java:1667) 
        at com.oneplus.camera.io.PhotoSaveTask.onPrepareMediaStoreValues(PhotoSaveTask.java:567) 
        at com.oneplus.camera.io.MediaSaveTask.insertToMediaStore(MediaSaveTask.java:260) 
        at com.oneplus.camera.io.PhotoSaveTask.insertToMediaStore(PhotoSaveTask.java:367) 
        at com.oneplus.camera.io.FileManagerImpl$FileManageerThread$1.handleMessage(FileManagerImpl.java:515) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(

**Comment by adityathoutam** [comment]
I have replaced the .aar file, it still resulted in crash. Here is the updated logcat.

> 2020-02-04 15:35:16.147 18113-18721/? E/ImageUtils: decodeOrientation() - Fail to access file /devroot/data/data/APP_PACKAGE_NAME/cache/IMG_camera.jpg
>     java.io.FileNotFoundException: /devroot/data/data/APP_PACKAGE_NAME/cache/IMG_camera.jpg: open failed: ENOENT (No such file or directory)
>         at libcore.io.IoBridge.open(IoBridge.java:496)
>         at java.io.FileInputStream.<init>(FileInputStream.java:159)
>         at java.io.FileInputStream.<init>(FileInputStream.java:115)
>         at com.oneplus.media.ImageUtils.decodeOrientation(ImageUtils.java:1667)
>         at com.oneplus.camera.io.PhotoSaveTask.onPrepareMediaStoreValues(PhotoSaveTask.java:567)
>         at com.oneplus.camera.io.MediaSaveTask.insertToMediaStore(MediaSaveTask.java:260)
>         at com.oneplus.camera.io.PhotoSaveTask.insertToMediaStore(PhotoSaveTask.java:367)
>         at com.oneplus.camera.io.FileManagerImpl$FileManageerThread$1.handleMessage(FileManagerImpl.java:515)
>         at android.os.Handler.dispatchMessage(Handler.java:107)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.os.HandlerThread.run(HandlerThread.java:67)
>      Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
>         at libcore.io.Linux.open(Native Method)
>         at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
>         at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
>         at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
>         at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7581)
>         at libcore.io.IoBridge.open(IoBridge.java:482)
>         at java.io.FileInputStream.<init>(FileInputStream.java:159) 
>         at java.io.FileInputStream.<init>(FileInputStream.java:115) 
>         at com.oneplus.media.ImageUtils.decodeOrientation(ImageUtils.java:1667) 
>         at com.oneplus.camera.io.PhotoSaveTask.onPrepareMediaStoreValues(PhotoSaveTask.java:567) 
>         at com.oneplus.camera.io.MediaSaveTask.insertToMediaStore(MediaSaveTask.java:260) 
>         at com.oneplus.camera.io.PhotoSaveTask.insertToMediaStore(PhotoSaveTask.java:367) 
>         at com.oneplus.camera.io.FileManagerImpl$FileManageerThread$1.handleMessage(FileManagerImpl.java:515) 
>         at android.os.Handler.dispatchMessage(Handler.java:107) 
>         at android.os.Looper.loop(Looper.java:214) 
>         at android.os.HandlerThread.run(

**Comment by yasirkula** [comment]
Made one final change, hope it works: [NativeCamera.zip](https://github.com/yasirkula/UnityNativeCamera/files/4152816/NativeCamera.zip)

**Comment by adityathoutam** [comment]
Still the same. I noticed

`> java.io.FileInputStream`
is now changed to 
`> java.io.FileInputStream.<init>`
in the logcat

> 2020-02-04 17:06:14.350 21654-25679/? E/ImageUtils: decodeOrientation() - Fail to access file /devroot/data/data/APP_PACKAGE_NAME/cache/IMG_camera.jpg
    java.io.FileNotFoundException: /devroot/data/data/APP_PACKAGE_NAME/cache/IMG_camera.jpg: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at com.oneplus.media.ImageUtils.decodeOrientation(ImageUtils.java:1667)
        at com.oneplus.camera.io.PhotoSaveTask.onPrepareMediaStoreValues(PhotoSaveTask.java:567)
        at com.oneplus.camera.io.MediaSaveTask.insertToMediaStore(MediaSaveTask.java:260)
        at com.oneplus.camera.io.PhotoSaveTask.insertToMediaStore(PhotoSaveTask.java:367)
        at com.oneplus.camera.io.FileManagerImpl$FileManageerThread$1.handleMessage(FileManagerImpl.java:515)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7581)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        at java.io.FileInputStream.<init>(FileInputStream.java:159) 
        at java.io.FileInputStream.<init>(FileInputStream.java:115) 
        at com.oneplus.media.ImageUtils.decodeOrientation(ImageUtils.java:1667) 
        at com.oneplus.camera.io.PhotoSaveTask.onPrepareMediaStoreValues(PhotoSaveTask.java:567) 
        at com.oneplus.camera.io.MediaSaveTask.insertToMediaStore(MediaSaveTask.java:260) 
        at com.oneplus.camera.io.PhotoSaveTask.insertToMediaStore(PhotoSaveTask.java:367) 
        at com.oneplus.camera.io.FileManagerImpl$FileManageerThread$1.handleMessage(FileManagerImpl.java:515) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by yasirkula** [comment]
Thank you for all the feedback. At this point, I can't really tell why this is happening. Seeing `/devroot/`, I'm guessing that the device is rooted. Perhaps this is an issue on OnePlus's side that got fixed in later updates but because the device is rooted, it didn't receive these updates (some search results for "oneplus android save to gallery crash" say that certain crashes are fixed after updating the OS).

**Comment by adityathoutam** [comment]
The device is Oneplus 7 Pro. And it is not rooted and is on latest OTA build.
Anyway I'll try it in other devices and re-open this issue, if I encounter it.
Thank you for your prompt response.
